// Pure iCalendar (RFC 5545) logic — NO tsdav / expo-crypto imports, so this module
// is unit-testable offline (the property-preservation test is the plan's #1 risk).
import IcalExpander from 'ical-expander';
import ICAL from 'ical.js';

import type { CalEvent, EventInput } from './types';

/**
 * Expand one calendar object's ICS into concrete CalEvents overlapping [start, end).
 * Handles single and recurring events uniformly via ical-expander.
 */
export function expandEvents(
  ics: string,
  url: string,
  etag: string,
  rangeStart: Date,
  rangeEnd: Date,
): CalEvent[] {
  const expander = new IcalExpander({ ics, maxIterations: 1000 });
  const { events, occurrences } = expander.between(rangeStart, rangeEnd);

  const map = (event: any, startTime: any, endTime: any): CalEvent => {
    const vevent = event.component; // the VEVENT ICAL.Component
    const uid: string = event.uid;
    return {
      id: `${uid}:${startTime.toString()}`,
      url,
      etag,
      uid,
      summary: event.summary ?? '',
      start: startTime.toJSDate(),
      end: endTime.toJSDate(),
      allDay: Boolean(startTime.isDate),
      location: vevent.getFirstPropertyValue('location') ?? undefined,
      description: vevent.getFirstPropertyValue('description') ?? undefined,
      raw: ics,
    };
  };

  return [
    ...events.map((e: any) => map(e, e.startDate, e.endDate)),
    ...occurrences.map((o: any) => map(o.item, o.startDate, o.endDate)),
  ];
}

function allDayTime(d: Date) {
  return new ICAL.Time(
    {
      year: d.getFullYear(),
      month: d.getMonth() + 1,
      day: d.getDate(),
      isDate: true,
    },
    ICAL.Timezone.localTimezone,
  );
}

/**
 * Build a new VCALENDAR string for a create. `uid` is passed in (generated by the
 * caller via expo-crypto) so this stays crypto-free and testable. Timed events are
 * written as UTC (`Z`) to avoid needing a registered VTIMEZONE (first-cut decision).
 */
export function buildEventICS(input: EventInput, uid: string): string {
  const vcalendar = new ICAL.Component(['vcalendar', [], []]);
  vcalendar.updatePropertyWithValue('prodid', '-//mitsume//caldav//EN');
  vcalendar.updatePropertyWithValue('version', '2.0');

  const vevent = new ICAL.Component('vevent');
  const event = new ICAL.Event(vevent);
  event.uid = uid;
  event.summary = input.summary;

  if (input.allDay) {
    const start = allDayTime(input.start);
    const end = allDayTime(input.end);
    end.day += 1; // DTEND is non-inclusive
    event.startDate = start;
    event.endDate = end;
  } else {
    event.startDate = ICAL.Time.fromJSDate(input.start, true); // useUTC
    event.endDate = ICAL.Time.fromJSDate(input.end, true);
  }

  if (input.location) vevent.updatePropertyWithValue('location', input.location);
  if (input.description) vevent.updatePropertyWithValue('description', input.description);
  vevent.updatePropertyWithValue('dtstamp', ICAL.Time.now());

  vcalendar.addSubcomponent(vevent);
  return vcalendar.toString();
}

/**
 * Edit an existing event while PRESERVING unknown properties (X-APPLE-*, ATTENDEE,
 * ORGANIZER, …). Parse the original tree and mutate ONLY changed fields — never
 * rebuild a VEVENT from scratch (that is what drops data). Plan's #1 correctness risk.
 */
export function editPreserving(
  ics: string,
  changes: Partial<Pick<EventInput, 'summary' | 'start' | 'end' | 'location' | 'description'>>,
): string {
  const vcalendar = new ICAL.Component(ICAL.parse(ics));
  const vevent = vcalendar.getFirstSubcomponent('vevent');
  if (!vevent) return ics;

  if (changes.summary !== undefined) vevent.updatePropertyWithValue('summary', changes.summary);
  if (changes.location !== undefined) vevent.updatePropertyWithValue('location', changes.location);
  if (changes.description !== undefined) {
    vevent.updatePropertyWithValue('description', changes.description);
  }
  if (changes.start) vevent.updatePropertyWithValue('dtstart', ICAL.Time.fromJSDate(changes.start, true));
  if (changes.end) vevent.updatePropertyWithValue('dtend', ICAL.Time.fromJSDate(changes.end, true));

  // Bump revision metadata only — do NOT touch X-APPLE-*, ATTENDEE, ORGANIZER.
  vevent.updatePropertyWithValue('last-modified', ICAL.Time.now());
  const seq = Number(vevent.getFirstPropertyValue('sequence') ?? 0);
  vevent.updatePropertyWithValue('sequence', seq + 1);

  return vcalendar.toString();
}
