// Pure iCalendar (RFC 5545) logic — NO tsdav / expo-crypto imports, so this module
// is unit-testable offline (the property-preservation test is the plan's #1 risk).
import IcalExpander from 'ical-expander';
import ICAL from 'ical.js';

import type { CalEvent, EventChanges, EventInput } from './types';

/**
 * Expand one calendar object's ICS into concrete CalEvents overlapping [start, end).
 * Handles single and recurring events uniformly via ical-expander.
 */
export function expandEvents(
  ics: string,
  url: string,
  etag: string,
  rangeStart: Date,
  rangeEnd: Date,
): CalEvent[] {
  const expander = new IcalExpander({ ics, maxIterations: 1000 });
  const { events, occurrences } = expander.between(rangeStart, rangeEnd);

  const map = (event: any, startTime: any, endTime: any): CalEvent => {
    const vevent = event.component; // the VEVENT ICAL.Component
    const uid: string = event.uid;
    return {
      id: `${uid}:${startTime.toString()}`,
      url,
      etag,
      uid,
      summary: event.summary ?? '',
      start: startTime.toJSDate(),
      end: endTime.toJSDate(),
      allDay: Boolean(startTime.isDate),
      location: vevent.getFirstPropertyValue('location') ?? undefined,
      description: vevent.getFirstPropertyValue('description') ?? undefined,
      raw: ics,
    };
  };

  return [
    ...events.map((e: any) => map(e, e.startDate, e.endDate)),
    ...occurrences.map((o: any) => map(o.item, o.startDate, o.endDate)),
  ];
}

/** All-day ICAL.Time (VALUE=DATE) from a local Date. */
function toAllDayTime(d: Date) {
  return new ICAL.Time(
    {
      year: d.getFullYear(),
      month: d.getMonth() + 1,
      day: d.getDate(),
      isDate: true,
    },
    ICAL.Timezone.localTimezone,
  );
}

/**
 * DTSTART/DTEND pair for an event. Timed events are written as UTC (`Z`) to avoid
 * needing a registered VTIMEZONE (first-cut decision); all-day events get a
 * VALUE=DATE pair with the non-inclusive DTEND (+1 day).
 */
function toTimePair(start: Date, end: Date, allDay: boolean) {
  if (!allDay) {
    return {
      start: ICAL.Time.fromJSDate(start, true), // useUTC
      end: ICAL.Time.fromJSDate(end, true),
    };
  }
  const endTime = toAllDayTime(end);
  endTime.day += 1; // DTEND is non-inclusive
  return { start: toAllDayTime(start), end: endTime };
}

/**
 * Build a new VCALENDAR string for a create. `uid` is passed in (generated by the
 * caller via expo-crypto) so this stays crypto-free and testable.
 */
export function buildEventICS(input: EventInput, uid: string): string {
  const vcalendar = new ICAL.Component(['vcalendar', [], []]);
  vcalendar.updatePropertyWithValue('prodid', '-//mitsume//caldav//EN');
  vcalendar.updatePropertyWithValue('version', '2.0');

  const vevent = new ICAL.Component('vevent');
  const event = new ICAL.Event(vevent);
  event.uid = uid;
  event.summary = input.summary;

  // ICAL.Event setters manage the TZID parameter / VALUE=DATE type correctly.
  const { start, end } = toTimePair(input.start, input.end, input.allDay);
  event.startDate = start;
  event.endDate = end;

  if (input.location) vevent.updatePropertyWithValue('location', input.location);
  if (input.description) vevent.updatePropertyWithValue('description', input.description);
  vevent.updatePropertyWithValue('dtstamp', ICAL.Time.now());

  vcalendar.addSubcomponent(vevent);
  return vcalendar.toString();
}

/**
 * Edit an existing event while PRESERVING unknown properties (X-APPLE-*, ATTENDEE,
 * ORGANIZER, …). Parse the original tree and mutate ONLY the provided fields — never
 * rebuild a VEVENT from scratch (that is what drops data). Plan's #1 correctness risk.
 *
 * Whole-series semantics: for a recurring event this rewrites the series DTSTART/DTEND.
 */
export function editPreserving(ics: string, changes: EventChanges): string {
  const vcalendar = new ICAL.Component(ICAL.parse(ics));
  const vevent = vcalendar.getFirstSubcomponent('vevent');
  if (!vevent) return ics;
  const event = new ICAL.Event(vevent);

  if (changes.summary !== undefined) event.summary = changes.summary;
  if (changes.location !== undefined) event.location = changes.location;
  if (changes.description !== undefined) event.description = changes.description;
  if (changes.start && changes.end) {
    // Event setters replace the TZID parameter / value type instead of leaving a
    // stale `;TZID=` next to a rewritten value (updatePropertyWithValue would).
    const { start, end } = toTimePair(changes.start, changes.end, changes.allDay ?? false);
    event.startDate = start;
    event.endDate = end;
  }

  // Bump revision metadata only — do NOT touch X-APPLE-*, ATTENDEE, ORGANIZER.
  vevent.updatePropertyWithValue('last-modified', ICAL.Time.now());
  const seq = Number(vevent.getFirstPropertyValue('sequence') ?? 0);
  vevent.updatePropertyWithValue('sequence', seq + 1);

  return vcalendar.toString();
}
